name: chain-test (temporary)
on:
  workflow_dispatch:
    inputs:
      hop:
        description: "recursion depth"
        default: "0"
concurrency:
  group: chain-test
  cancel-in-progress: false
jobs:
  t:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - run: echo "hop=${{ inputs.hop }}"
      - if: ${{ inputs.hop == '0' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run chain-test.yml --ref main -f hop=1
